<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\Dabom.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\Dabom.ico" />
    <Resource Include="Assets\TmdbLogo.png" />
    <Resource Include="..\..\assets\imdb.png" Link="Assets\imdb.png" />
    <Resource Include="..\..\assets\rotten_tomato.png" Link="Assets\rotten_tomato.png" />
  </ItemGroup>

</Project>
